# Generated by Django 3.0.6 on 2020-06-11 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_image', models.ImageField(null=True, upload_to='profile')),
                ('pet_explain', models.CharField(max_length=100)),
            ],
        ),
    ]
