# Generated by Django 3.0.6 on 2020-06-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200611_1642'),
        ('Profile', '0002_auto_20200611_1645'),
    ]

    operations = [
    ]
