# Generated by Django 3.0.3 on 2020-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200614_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pet_image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
