# Generated by Django 3.0.4 on 2020-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='images',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
