# Generated by Django 3.0.3 on 2020-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='images',
            field=models.ImageField(default='static/img/footprint.gif', upload_to='%Y/%m/%d/%H/%m'),
        ),
    ]
