# Generated by Django 3.0.3 on 2020-06-11 13:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
