# Generated by Django 3.0.3 on 2020-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200614_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='images',
            field=models.ImageField(default='null', upload_to='%Y/%m/%d/%H/%m'),
        ),
    ]
