# Generated by Django 3.0.4 on 2020-06-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200604_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='%Y/%m/%d/%H/%m'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='comment')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Diary')),
            ],
        ),
    ]
