<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-06-09 10:54
=======
# Generated by Django 3.0.4 on 2020-06-09 10:29
>>>>>>> 68671c4956b2ed850745edce8c0e539611f2577d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diary_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
