# Generated by Django 3.0.3 on 2020-06-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diary_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
