<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-06-11 07:36
=======
# Generated by Django 3.0.4 on 2020-06-09 10:29

>>>>>>> 3fd894345c43d0e274376d08973d9bccedf89938

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diary_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
