# Generated by Django 2.2.7 on 2020-06-04 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='이름')),
                ('major', models.CharField(max_length=30, verbose_name='학과')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('m_or_f', models.CharField(choices=[('남', '남'), ('여', '여')], max_length=2, verbose_name='성별')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
