# Generated by Django 2.2.7 on 2020-06-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20200610_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NickName',
        ),
    ]
