# Generated by Django 3.0.4 on 2020-06-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20200610_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nickname',
            name='nickname',
        ),
    ]
